'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import {
  Loader2,
  Search,
  BookOpen,
  ExternalLink,
  Sparkles,
  AlertCircle,
  X,
  Download,
  Copy,
  Check,
  Clock,
  Plus,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { useDeepResearch } from '@/lib/stores/perplexity-finance-store';
import { ResearchMarkdown } from '@/components/research/ResearchMarkdown';

/**
 * DeepResearchPanel - Generate comprehensive AI research reports
 *
 * Features:
 * - Topic-based deep research
 * - Customizable focus areas
 * - Progress indicator for long-running requests
 * - Copy to clipboard
 * - Markdown export
 */

// Suggested focus areas
const SUGGESTED_FOCUS_AREAS = [
  'Market Size & Growth',
  'Competitive Landscape',
  'Key Risks',
  'Investment Thesis',
  'Technical Analysis',
  'Management Quality',
  'Financial Health',
  'Industry Trends',
  'Regulatory Environment',
  'ESG Factors',
];

interface DeepResearchPanelProps {
  className?: string;
}

export function DeepResearchPanel({ className }: DeepResearchPanelProps) {
  const [topic, setTopic] = useState('');
  const [focusAreas, setFocusAreas] = useState<string[]>([]);
  const [customFocus, setCustomFocus] = useState('');
  const [copied, setCopied] = useState(false);

  const {
    research,
    researchLoading,
    researchError,
    researchProgress,
    generateDeepResearch,
    clearResearch,
  } = useDeepResearch();

  const handleGenerate = () => {
    if (!topic.trim()) return;
    generateDeepResearch(
      topic.trim(),
      focusAreas.length > 0 ? focusAreas : undefined
    );
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleGenerate();
    }
  };

  const toggleFocusArea = (area: string) => {
    setFocusAreas((prev) =>
      prev.includes(area) ? prev.filter((a) => a !== area) : [...prev, area]
    );
  };

  const addCustomFocus = () => {
    if (customFocus.trim() && !focusAreas.includes(customFocus.trim())) {
      setFocusAreas((prev) => [...prev, customFocus.trim()]);
      setCustomFocus('');
    }
  };

  const handleCopy = async () => {
    if (!research?.content) return;
    await navigator.clipboard.writeText(research.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    if (!research?.content) return;

    const markdown = `# Deep Research Report: ${research.topic}

Generated: ${new Date(research.generatedAt).toLocaleString()}
${research.focusAreas ? `Focus Areas: ${research.focusAreas.join(', ')}` : ''}

---

${research.content}

---

## Sources
${research.citations?.map((c, i) => `${i + 1}. ${c}`).join('\n') || 'No citations available'}

---

*Generated by DeepStack AI Research powered by Perplexity Finance*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `research-${topic.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Format time since generation
  const formatGeneratedAt = (isoDate?: string) => {
    if (!isoDate) return '';
    const date = new Date(isoDate);
    return date.toLocaleString();
  };

  return (
    <div className={cn('h-full flex flex-col p-4 gap-4', className)}>
      {/* Header */}
      <div className="flex items-center justify-between flex-shrink-0">
        <div className="flex items-center gap-2">
          <BookOpen className="h-5 w-5 text-primary" />
          <h2 className="text-lg font-semibold">Deep Research</h2>
        </div>
        {research && (
          <div className="flex items-center gap-1">
            <Button variant="ghost" size="sm" onClick={handleCopy}>
              {copied ? (
                <Check className="h-3.5 w-3.5 mr-1" />
              ) : (
                <Copy className="h-3.5 w-3.5 mr-1" />
              )}
              {copied ? 'Copied' : 'Copy'}
            </Button>
            <Button variant="ghost" size="sm" onClick={handleExport}>
              <Download className="h-3.5 w-3.5 mr-1" />
              Export
            </Button>
            <Button variant="ghost" size="sm" onClick={clearResearch}>
              <X className="h-3.5 w-3.5 mr-1" />
              Clear
            </Button>
          </div>
        )}
      </div>

      {/* Input Form */}
      <Card className="flex-shrink-0">
        <CardContent className="py-3 px-3 space-y-3">
          {/* Topic Input */}
          <div className="space-y-1.5">
            <Label htmlFor="topic" className="text-xs">
              Research Topic
            </Label>
            <Textarea
              id="topic"
              placeholder="Enter a topic to research (e.g., 'AI semiconductor industry outlook 2024', 'Tesla competitive positioning')"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              onKeyDown={handleKeyDown}
              className="min-h-[60px] text-sm resize-none"
              rows={2}
            />
          </div>

          {/* Focus Areas */}
          <div className="space-y-1.5">
            <Label className="text-xs">Focus Areas (optional)</Label>
            <div className="flex flex-wrap gap-1.5">
              {SUGGESTED_FOCUS_AREAS.map((area) => (
                <Badge
                  key={area}
                  variant={focusAreas.includes(area) ? 'default' : 'outline'}
                  className="text-[10px] cursor-pointer"
                  onClick={() => toggleFocusArea(area)}
                >
                  {area}
                </Badge>
              ))}
            </div>

            {/* Custom Focus */}
            <div className="flex gap-2 mt-2">
              <Input
                placeholder="Add custom focus area"
                value={customFocus}
                onChange={(e) => setCustomFocus(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && addCustomFocus()}
                className="h-7 text-xs"
              />
              <Button
                variant="outline"
                size="sm"
                className="h-7"
                onClick={addCustomFocus}
                disabled={!customFocus.trim()}
              >
                <Plus className="h-3 w-3" />
              </Button>
            </div>

            {/* Selected Focus Areas */}
            {focusAreas.length > 0 && (
              <div className="flex flex-wrap gap-1 mt-2">
                <span className="text-[10px] text-muted-foreground mr-1">
                  Selected:
                </span>
                {focusAreas.map((area) => (
                  <Badge
                    key={area}
                    variant="secondary"
                    className="text-[10px]"
                    onClick={() => toggleFocusArea(area)}
                  >
                    {area}
                    <X className="h-2 w-2 ml-1" />
                  </Badge>
                ))}
              </div>
            )}
          </div>

          {/* Generate Button */}
          <div className="flex justify-end">
            <Button
              size="sm"
              onClick={handleGenerate}
              disabled={!topic.trim() || researchLoading}
            >
              {researchLoading ? (
                <Loader2 className="h-3.5 w-3.5 mr-1 animate-spin" />
              ) : (
                <Sparkles className="h-3.5 w-3.5 mr-1" />
              )}
              Generate Research (50 credits)
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Progress / Results */}
      <div className="flex-1 min-h-0">
        {researchError ? (
          <Card className="h-full flex items-center justify-center">
            <div className="flex flex-col items-center gap-2 text-destructive">
              <AlertCircle className="h-8 w-8" />
              <span className="text-sm">{researchError}</span>
              <Button variant="outline" size="sm" onClick={handleGenerate}>
                Retry
              </Button>
            </div>
          </Card>
        ) : researchLoading ? (
          <Card className="h-full flex items-center justify-center">
            <div className="flex flex-col items-center gap-4 w-64">
              <Loader2 className="h-10 w-10 animate-spin text-primary" />
              <div className="text-center">
                <p className="text-sm font-medium">Generating Deep Research</p>
                <p className="text-xs text-muted-foreground mt-1">
                  This may take 1-2 minutes...
                </p>
              </div>
              <Progress value={researchProgress} className="w-full" />
              <span className="text-xs text-muted-foreground">
                {researchProgress}% complete
              </span>
            </div>
          </Card>
        ) : research ? (
          <Card className="h-full flex flex-col">
            <CardHeader className="py-2 px-3 flex-shrink-0">
              <CardTitle className="text-sm flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <BookOpen className="h-4 w-4" />
                  <span className="truncate max-w-[300px]">{research.topic}</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                    <Clock className="h-2.5 w-2.5" />
                    {formatGeneratedAt(research.generatedAt)}
                  </span>
                  {research.mock && (
                    <span className="text-[10px] px-1.5 py-0.5 bg-yellow-500/20 text-yellow-600 dark:text-yellow-400 rounded">
                      Mock
                    </span>
                  )}
                </div>
              </CardTitle>
              {research.focusAreas && research.focusAreas.length > 0 && (
                <div className="flex flex-wrap gap-1 mt-1">
                  {research.focusAreas.map((area, idx) => (
                    <Badge key={idx} variant="outline" className="text-[10px]">
                      {area}
                    </Badge>
                  ))}
                </div>
              )}
            </CardHeader>

            <Separator />

            <ScrollArea className="flex-1 p-3">
              <ResearchMarkdown content={research.content} />

              {/* Citations */}
              {research.citations && research.citations.length > 0 && (
                <>
                  <Separator className="my-4" />
                  <div className="space-y-2">
                    <h4 className="text-xs font-medium">Sources & References</h4>
                    <div className="space-y-1.5">
                      {research.citations.map((citation, idx) => (
                        <a
                          key={idx}
                          href={citation}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center gap-2 text-xs text-primary hover:underline bg-primary/5 px-2 py-1.5 rounded"
                        >
                          <span className="text-muted-foreground">{idx + 1}.</span>
                          <ExternalLink className="h-3 w-3 flex-shrink-0" />
                          <span className="truncate">{citation}</span>
                        </a>
                      ))}
                    </div>
                  </div>
                </>
              )}
            </ScrollArea>

            {/* Footer */}
            <div className="px-3 py-2 border-t flex items-center justify-between">
              <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                <Sparkles className="h-2.5 w-2.5" />
                Deep Research by Perplexity Finance
              </span>
              <div className="flex items-center gap-2">
                <Button variant="ghost" size="sm" className="h-6" onClick={handleCopy}>
                  {copied ? (
                    <Check className="h-3 w-3" />
                  ) : (
                    <Copy className="h-3 w-3" />
                  )}
                </Button>
                <Button variant="ghost" size="sm" className="h-6" onClick={handleExport}>
                  <Download className="h-3 w-3" />
                </Button>
              </div>
            </div>
          </Card>
        ) : (
          <Card className="h-full flex items-center justify-center">
            <div className="flex flex-col items-center gap-3 text-muted-foreground max-w-md">
              <BookOpen className="h-12 w-12 opacity-50" />
              <div className="text-center">
                <p className="text-sm font-medium">AI Deep Research</p>
                <p className="text-xs mt-1">
                  Generate comprehensive research reports on any topic with AI
                </p>
              </div>
              <div className="text-[10px] text-center text-muted-foreground/70 mt-2">
                Deep research uses advanced AI to analyze multiple sources and generate
                detailed, well-cited reports. This typically takes 1-2 minutes and costs 50 credits.
              </div>
            </div>
          </Card>
        )}
      </div>
    </div>
  );
}

export default DeepResearchPanel;
